# RDF Vocabulary to Dart Configuration
# This file configures the build_runner for generating Dart classes from RDF vocabularies.

targets:
  $default:
    builders:
      # Builder identifier in the format <package_name>|<builder_name>
      # Used to reference this builder in dependencies
      rdf_vocabulary_to_dart|rdf_to_dart_generator:
        enabled: true
        options:
          # Path to the JSON file containing the vocabulary IRIs to be processed
          # This file should contain a list of IRIs pointing to RDF vocabularies
          vocabulary_config_path: "lib/src/all.vocabulary_sources.vocab.json"
          # Directory where generated Dart files will be output
          output_dir: "lib/src/generated"
