name: rdf_vocabularies
description: A collection of well known RDF vocabularies as Dart constants, grouped in classes.
version: 0.4.3
homepage: https://kkalass.github.io/rdf_vocabularies/
repository: https://github.com/kkalass/rdf_vocabularies
issue_tracker: https://github.com/kkalass/rdf_vocabularies/issues
documentation: https://kkalass.github.io/rdf_vocabularies/
topics:
  - rdf
  - linked-data
  - semantic-web
readme: README.md
changelog: CHANGELOG.md
license: LICENSE
maintainers:
  - "Klas Kalaß <habbatical@gmail.com>"

environment:
  sdk: ^3.7.0

dependencies:
  rdf_vocabularies_core: ^0.4.2
  rdf_vocabularies_schema: ^0.4.2
  rdf_vocabularies_schema_http: ^0.4.2
  rdf_core: ^0.9.11

dev_dependencies:
  test: ^1.21.0
  lints: ">=5.1.1 <7.0.0"
  yaml: ^3.1.2
  path: ^1.8.0
